### ISSUE TITLE
conversation table reloaded for ever 

### ISSUE THREAD

**Issue by mrpower55** [tigase/siskin-im#127] opened 2021-08-12 10:51 UTC
Hello,

i have take a look to new version of siskin and i found that conversation page is reloaded the table for ever, after i check i found on ConversationDataSourceDelegate there is function updateStore(scrollTo: ScrollTo = .none, completionHandler: (()->Void)? = nil) call table reloaddata function for each changes that happened on store

i am trying to solve the problem but without any results :(

so please can you help us to fix it?

thanks

**Comment by hantu85** [comment] 2021-08-12 15:12
Thank you for reporting the issue. Will will look into it, but please keep in mind that the version in `master` branch (or from TestFlight) may be unstable and it is for testing only. 

If you need a stable version it is available in AppStore with sources available in`stable` branch.

**Comment by hantu85** [comment] 2021-08-15 10:42
I was not able to look at the issue, but most likely the issue is caused by the mechanism responsible for loading older entries when we are at the end of entries cached in memory when there are no more entries to load.

**Comment by hantu85** [comment] 2021-09-16 17:59
The issue is now fixed in the latest build available in TestFlight.

**Closed by hantu85** 2021-09-16 17:59 UTC
Labels: bug
