### ISSUE TITLE
iOS share button sends message in plaintext where OMEMO is enabled

### ISSUE THREAD

**Issue by werner291** [tigase/siskin-im#247] opened 2024-11-12 11:23 UTC
**Describe the bug**

When using the iOS "share" button (from Reddit) in this case, the message is sent in plaintext, even though other messages use OMEMO.

**To Reproduce**
1. Click the "share" button on a Reddit post.
2. Select Siskin, and then the chat (which previously used OMEMO for all messages)
3. Observe that the message was sent in plaintext (no padlock in Siskin; red padlock in Gajim)

**Expected behavior**

The "share" feature should use the same encryption mode as other messages in the chat.

**Screenshots**

**Details (please complete the following information):**
 - Siskin Version: 7.3.3
 - iOS version: 16.7.10
 - iPhone model: iPhone 8

**Additional context**

Not sure. I just usually chat with this contact over OMEMO, yet here the message was sent in plaintext for some reason.

**Comment by hantu85** [comment] 2024-11-12 11:38
Duplicate of issue #67

**Closed as not planned** 2024-11-12 11:38 UTC
Labels: bug
