### ISSUE TITLE
Siskin uploads encrypted photos to unencrypted MUC

### ISSUE THREAD

**Issue by ingoj** [tigase/siskin-im#52] opened 2020-08-13 14:32 UTC
**Describe the bug**
Uploaded a screenshot from iPhone to MUC at fotografie@room.pix-art.de and received question why I uploaded an encrypted photo to an unencrypted MUC, here's what Ge0rg sent me via 1:1 chat: 

`16:56:46 ij> aesgcm://files.hookipa.net/upload/c561ea35e2a7993ef84a0ab68c8e7d978ab29458/dXYqs0urMsrzLt7TC3BsLC63DJpJzpINTr2epPZk/image.jpg#9a9710625263ec633576b4f1dc95a05229fe71d141b2706cfe2afd7e6d6e005fc57d7bb89f658d48b2543551`

According to feedback in the MUC it was delivered together with the OMEMO key

**Details (please complete the following information):**
 - Siskin Version: 5.8.1
 - iOS version: 13.6
 - iPhone model: iPhone SE

**Comment by huhndev** [comment] 2020-08-14 08:03
I was just able to reproduce the bug. A file is sent encrypted by Siskin in both public and private mucs.

```
<message id="E1FA491B-061A-4C9E-8CD8-23D761D088D4" type="groupchat" to="georgeorwell@henhouse.im/profanity.0Mgf" lang="en" from="test-muc@conference.henhouse.im/testing"><archived id="1597391849388171"
           by="test-muc@conference.henhouse.im" xmlns="urn:xmpp:mam:tmp"/><stanza-id id="1597391849388171" by="test-muc@conference.henhouse.im" xmlns="urn:xmpp:sid:0"/><x xmlns="jabber:x:oob"><url>aesgcm://henhouse.im:5443/upload/7c9f20f95
           b675e64cff397f2d78c1f0e9a77e8c4/c3xpR4QgFxyHv2Gy7bJ3vgat9D45ExoihcmoPJQT/image.jpg#0182a427303abade3d2891a4ad94e867e4445c17d173fd3685efdeed29b80ac33b2c90fc12ac12f09f651f67</url></x><body>aesgcm://henhouse.im:5443/upload/7c9f20f9
           5b675e64cff397f2d78c1f0e9a77e8c4/c3xpR4QgFxyHv2Gy7bJ3vgat9D45ExoihcmoPJQT/image.jpg#0182a427303abade3d2891a4ad94e867e4445c17d173fd3685efdeed29b80ac33b2c90fc12ac12f09f651f67</body></message>
```

- Siskin Version: Beta 6.0
- iOS version: 13.6.1
- iPhone model: 8

**Comment by hantu85** [comment] 2020-08-14 08:25
Could you verify, that in SiskinIM settings in the chat section, encryption value is set to OMEMO? If so, then enforcing OMEMO on all newly opened chats and joined rooms may be source of this issue.

**Comment by ingoj** [comment] 2020-08-14 08:35
Yes, under Chat Settings Encryption is set to "OMEMO" here...

**Comment by huhndev** [comment] 2020-08-14 08:37
@hantu85, you're right. The encryption is set to OMEMO. After I deactivate it, files are sent unencrypted again in mucs.

**Comment by hantu85** [comment] 2020-08-17 14:57
The issue is now fixed in the code and fix will be part of the next build.

**Closed** 2020-10-14 12:21 UTC
Labels: bug
