### ISSUE TITLE
the oob image preview not working with omemo

### ISSUE THREAD

**Issue by mightyBroccoli** [tigase/siskin-im#4] opened 2019-09-27 19:04 UTC
**Describe the bug**
Client message encryption set to *None*
If the client sends an image with http upload to someone the preview is shown correctly.

Client message encryption set to *Omemo*
If the client sends an image with http upload to someone the preview is not shown.

**To Reproduce**
1. set message encryption to *None*
2. take a fancy picture and send it to someone
3. they can happily enjoy the preview
4. set message encryption to *Omemo*
5. take another fancy picture and send it to someone
6. they can not enjoy the preview

**Expected behavior**
The preview should be shown either way.

**Screenshots**
![Screenshot_20190927-205736_Conversations](https://user-images.githubusercontent.com/14238117/65795246-1f55a400-e16a-11e9-98bf-6da2261a6c35.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 5s
 - OS: iOS12.4.1
 - Browser default browser

**Comment by hantu85** [comment] 2019-09-28 08:22
This "issue" is caused by the fact that OMEMO is not encrypting links sent as OOB only message body. Due to the fact that SiskinIM does not support AESGCM at this point for encryption of transferred files, we decide to allow file transfer but not to send OOB but just a link in the message body. This decision was because of security reasons and will not be changed until we ship support for AESGCM.

The alternative solution would be for Conversations to check if the message body is a link and show a preview if it is a link to the image.

**Comment by hantu85** [comment] 2020-02-06 16:30
Now SiskinIM supports encrypted file transfer for OMEMO encrypted chats and file previews should be presented correctly without OOB.

**Closed by hantu85** 2020-02-06 16:30 UTC
