### ISSUE TITLE
Omemo keychain support

### ISSUE THREAD

**Issue by mightyBroccoli** [tigase/siskin-im#3] opened 2019-08-25 20:40 UTC
It seems that Siskin always reinitiates the remote keychain, resulting from possible other devices being remove.

Tested with Monal and Siskin on the same device.

Additionally Siskin does not request the keychain of a contact when starting a conversation. It only displays the already seen keys in the bundle.

**Comment by hantu85** [comment] 2019-09-04 08:24
Could you clarify a little what you think is happening? Is other device id removed from deviceslist of OMEMO PubSub node? or something else is happening?

**Comment by derHSE** [comment] 2019-09-04 09:59
I can confirm this part from mightyBroccoli: "Additionally Siskin does not request the keychain of a contact when starting a conversation". Way is dismail.de (Prosody) account with Siskin to conversations.im (ejabberd) account with conversations app

**Comment by hantu85** [comment] 2019-09-04 10:02
As for retrieval of contacts keychain (device id/bundle), it retrieves device keys only for devices that are listed on contact `deviceslist` and which is delivered by PEP (`+notify`).

**Comment by mightyBroccoli** [comment] 2019-09-05 16:15
> Could you clarify a little what you think is happening? Is other device id removed from deviceslist of OMEMO PubSub node? or something else is happening?

Sure thing. My test device has various iOS XMPP clients installed, all connected with the same account. Which should result in a keychain containing a key for each device.

By removing clients for the equation  I found that Siskin replaces the whole keychain when connecting. Which results in a "fresh" keychain, after the successful connection. I am unsure if this occurs every time siskin connects, but it happened quite often to be ux breaking.

By "fresh" keychain I do mean a keychain containing only siskins omemo key.

**Comment by hantu85** [comment] 2019-09-05 16:19
OK, it looks like this is the same issue as I've tracked down and fixed yesterday. New versions of Siskin IM and Beagle IM will have a fix for this issue.

**Comment by mightyBroccoli** [comment] 2019-09-05 17:12
That is awesome. Thank you for your effort.

**Closed** 2021-08-13 12:29 UTC
